name: Monitor AWS Provider Changes
on:
  push:
    paths:
      - 'CHANGELOG.md'
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify-changes:
    runs-on: ubuntu-latest
    permissions: 
      actions: write
      contents: write
      repository-projects: write
    steps:
      - name: Trigger second repository workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'creazer-v',
              repo: 'Terraform',
              event_type: 'aws-provider-update',
              client_payload: {
                source: context.repo.full_name
              }
            });
