name: Track AWS Provider Changes
on:
  push:
    paths:
      - 'CHANGELOG.md'
    branches:
      - main
  workflow_dispatch:

jobs:
  process-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and filter original changelog
        run: |
          curl -s https://raw.githubusercontent.com/hashicorp/terraform-provider-aws/main/CHANGELOG.md | \
          awk '
          BEGIN {
            printing = 0
            section = ""
          }
          /^## [0-9]+\.[0-9]+\.[0-9]+/ {
            print "\n" $0 "\n"
            printing = 1
            next
          }
          /^FEATURES:/ {
            if (printing) {
              print "\nFEATURES:"
              section = "FEATURES"
            }
            next
          }
          /^ENHANCEMENTS:/ {
            if (printing) {
              print "\nENHANCEMENTS:"
              section = "ENHANCEMENTS"
            }
            next
          }
          /^BUG FIXES:/ {
            if (printing) {
              print "\nBUG FIXES:"
              section = "BUG FIXES"
            }
            next
          }
          /rds|dynamodb|docdb|[^a-zA-Z]db[^a-zA-Z]|redshift|aurora/ {
            if (printing && section != "") {
              print $0
            }
          }
          ' > db_changes.md

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add db_changes.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update db_changes.md with filtered changelog entries" && git push)
